---
.gitignore:
  required:
    - ---.project

.gitlab-ci.yml:
  unmanaged: true

.travis.yml:
  docker_sets:
    - set: docker/centos-7
    - set: docker/ubuntu-14.04
  docker_defaults:
    bundler_args: ""
    script: bundle exec rake beaker
  secure: ""
  global_env:
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
    - GEM_BOLT=true
  branches:
    - release
  remove_includes:
    - env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.4
    - env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec RUBYGEMS_VERSION=2.7.8
      rvm: 2.1.9

.yardopts:
  optional:
    - --output-dir docs/

Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw
      - gem: bolt
        version: '~> 1.15'
        condition: ENV['GEM_BOLT']

Rakefile:
  requires:
    - puppet-lint/tasks/puppet-lint
  extras:
  extras: |
    # The beaker task requires the test fixtures created by the spec_prep task
    beaker_task_exists = Rake::Task.task_defined?('beaker')
    spec_prep_task_exists = Rake::Task.task_defined?('spec_prep')
    if beaker_task_exists && spec_prep_task_exists
      beaker_task = Rake::Task['beaker']
      spec_prep =  Rake::Task['spec_prep']
      beaker_task.enhance(beaker_task.prerequisite_tasks << spec_prep)
    end

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
