#!/opt/puppetlabs/puppet/bin/ruby

require 'puppet'

def status(provider)
  version = provider.properties[:ensure]
  latest = provider.latest
  if [:absent, :purged].include?(version)
    {status: 'absent', latest: latest}
  else
    if version != latest
      {status: 'out of date', version: version, latest: latest}
    else
      {status: 'up to date', version: version}
    end
  end
end

args = JSON.parse(STDIN.read)
package = args['name']
provider = args['provider']

opts = {:name => package}
opts[:provider] = provider if provider

begin
  provider = Puppet::Type.type(:package).new(opts).provider

  result = status(provider)
  puts result.to_json
  exit 0
rescue Puppet::Error => e
  puts({status: 'failure', error: e.message}.to_json)
  exit 1
end

